site_name: "Site EMC sur la democracie"
site_author: Classe Terminale EIPACA
site_url: https://eipaca.github.io/EMC_Democracie/

site_description: >-
  Site pour les classes de Terminales du Lycée EIPACA pour leur projet EMC axé sur la démocracie.

repo_url: https://github.com/eipaca/EMC_Democracie

copyright: |
  <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Licence Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a> Mise à disposition selon les termes de la <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Licence Creative Commons Attribution - Pas d’Utilisation Commerciale - Partage dans les Mêmes Conditions 4.0 International</a>.


theme:
  name: material
  font: false
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.prune 
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: fr
  
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Passer en mode sombre

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Passer en mode clair

  logo: assets/logo-ecole-internationale-paca-manosque.png

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/log-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16




extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # enables native support for Mermaid.js diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  #  enables content tabs
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


  # Page tree
nav:
  - Home: home.md
  - Articles: 
    - Les origines de la démocracies : Articles/Les-origines-de-la-democracie.md
    - La souveraineté du peuple: Articles/La-souverainete-du-peuple.md
    - La démocracie et les elections: Articles/La-democracie-et-les-elections.md
    - La laicité: Articles/La-laicite.md
    - La transformation des régimes politiques: Articles/La-transformation-des-regimes-politiques.md
    - La protections des démocracies: Articles/La-protections-des-democracies.md
    - La construction européenne: Articles/La-construction-europeenne.md
  - Lexique :
  - Biographies:
   - Droits civiques: Biographies/Droits-civiques.md
   - Intelectuels contemporains: Biographies/Intelectuels-contemporains.md
   - Personnalités politiques française: Biographies/Personnalites-politiques-française.md
   - Prix nobel de la paix: Biographies/Prix-nobel-de-la-paix.md
   - Ecrivains engagés: Biographies/Ecrivains-engages.md
   - Auteurs classiques: Biographies/Auteurs-classiques.md
   - Art et démocracie: Biographies/Art-et-democracie.md
   - Auteurs antiques: Biographies/Auteurs-antiques.md
   - Education et Democracie: Biographies/Education-et-democracie.md
   - Personalités française contemporraines: Biographies/Personalites-française-contemporraines.md
   - Démocratie et enjeux environnementaux: Biographies/Democratie-et-enjeux-environnementaux.md
  - Veille Radio :
   - Veille Radio Anglophone: Veille-Radio/Veille-Radio-Anglophone.md
   - Veille Radio Francophone: Veille-Radio/Veille-Radio-Francophone.md
  - Arts et Engagements Politiques:
   - Arts: Arts-et-Engagements-Politiques/Arts.md
   - Litterature: Arts-et-Engagements-Politiques/Litterature.md
   - Performance: Arts-et-Engagements-Politiques/Performance.md
  - Veille Presse:
   - Veille Presse Anglophone: Veille-Presse/Veille-Presse-Anglophone.md
   - Veille Presse Hispanophone: Veille-Presse/Veille-Presse-Hispanophone.md
   - Veille Presse Germanophone: Veille-Presse/Veille-Presse-Germanophone.md
   - Veille Presse Francophone: Veille-Presse/Veille-Presse-Francophone.md
  - Plus:
   - Journée événementielle: Plus/Journee-evenementielle.md
   - Journée 2021-2022: Plus/Journee-2021-2022.md
   - Journée 2022-2023: Plus/Journee-2022-2023.md
   - Enquêtes et sondages: Plus/Enquetes-et-sondages.md
   - Infographie Francophone: Plus/Infographie-Francophone.md
   - Infographie Anglophone: Plus/Infographie-Anglophone.md
